### ISSUE TITLE
Web UI doesn't working 

### ISSUE THREAD

**Issue by teo-tsou** [wavezhang/virtVNC#3]
I deployed all the components successfully. But when I visit http://NODEIP:NODEPORT/ the page is blank. The web console reported the following errors:

![Screenshot from 2021-08-06 14-16-50](https://user-images.githubusercontent.com/56459281/128502709-a820ace0-7a20-4308-8c07-bcb176ed0f13.png)

**Comment by wavezhang** [comment]
retry using Chrome？

**Comment by teo-tsou** [comment]
Thank you for the response! It's the same.
![Screenshot from 2021-08-11 03-58-02](https://user-images.githubusercontent.com/56459281/128953734-d39742b5-50d4-40cf-b1b9-237f98d363bd.png)

**Comment by wavezhang** [comment]
how do you  deploy this? Is it ok to curl http://NODEIP:NODEPORT/vendor/promise.js from cluster node?

**Comment by teo-tsou** [comment]
I deployed this by kubectl apply -f https://github.com/wavezhang/virtVNC/raw/master/k8s/virtvnc.yaml
When I curl http://NODEIP:NODEPORT/vendor/promise.js and I get 404 page not found.

http://NODEIP:NODEPORT/vendor/ contains only pako/lib/ directory

**Comment by wavezhang** [comment]
Does this files exists in virt-vnc pod ?

**Comment by teo-tsou** [comment]
Hello! No the file /vendor/promise.js doesn't exist inside the pod. But it contains /static/vendor/pako/lib directories.

**Comment by teo-tsou** [comment]
![image](https://user-images.githubusercontent.com/56459281/129998404-6ff66207-fb30-4b7d-9dd6-ec558e5ac5ca.png)

I believe the problem is in the function. But for sure you know better.

**Comment by wavezhang** [comment]
no /static/vendor/promise.js inside pod？You have a broken docker image?

**Comment by teo-tsou** [comment]
There's no such file. The pod is in running state. I deploy it by your repo.

**Comment by teo-tsou** [comment]
I solve it by changing the version of your docker image from v0.1 to master. The quay.io/samblade/virtvnc:v0.1 image doesn't contain promise.js. Thank you!
