### ISSUE TITLE
High latency

### ISSUE THREAD

**Issue by ManasPecenek** [wavezhang/virtVNC#4]
Hi,

I am testing Kubevirt by running a Windows VM on an Ubuntu machine (in Google Cloud) that has a KinD cluster installed. I went through all the steps and installed everything. Once I visited the URL **http://NODEIP:NODEPORT/**, in my case **http://VM_PUBLIC_IP:NODEPORT/**, I realized that there is a huge latency. When I move the cursor a bit, the cursor in the Windows responds after nearly 2 seconds. Thus, I wanted to ask what could be the reason behind it. Btw, I allocated 12GB of memory and 6 CPUs for the Windows VM.

**Comment by chenxinlong** [comment]
Hi, did you solve this problem ?

**Comment by ManasPecenek** [comment]
Unfortunately no. I started using a remote desktop service instead of virtVNC

**Comment by chenxinlong** [comment]
Hi, Can I have more details about the remote desktop service ?

**Comment by princesarvaiya** [comment]
@chenxinlong @ManasPecenek 

I have raised this issue, can you guys help me out please..

https://github.com/wavezhang/virtVNC/issues/6
