### ISSUE TITLE
hard to move cursor around the window

### ISSUE THREAD

**Issue by chenxinlong** [wavezhang/virtVNC#5]
![virtvnc](https://user-images.githubusercontent.com/9261954/189891798-13041e02-fa9c-4433-9f44-d73aefb28857.gif)

Like the gif upon, it's hard to move the cursor around the window freely.

**Comment by wavezhang** [comment]
Use tablet as default input device https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#tablet

See https://github.com/kubevirt/kubevirt/issues/1855

**Comment by chenxinlong** [comment]
Thx, I'll try this later.   Another question,  is there any way to change the picture size ?

**Comment by wavezhang** [comment]
modify resolution in windows?

**Comment by chenxinlong** [comment]
Ignore this.   I guess it's kubevirt's problem, kubevirt set a very low vram(16MB) for vga display, so I can't modify resolution.

Change the viedo type to `qxl` and raise the varm to 64 MB may helps.
